# Generated by Django 4.0.3 on 2022-03-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gabriel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gabriel',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
